allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

blockExoticSubdeps: true

dangerouslyAllowAllBuilds: false

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExcludePrune: true

minimumReleaseAgeStrict: true

overrides:
  uuid@<11.1.1: ^11.1.1

strictDepBuilds: true

strictStorePkgContentCheck: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - webpack-dev-middleware@7.4.6

trustPolicyExcludePrune: true

trustPolicyIgnoreAfter: 525600 # 1 year

update:
  githubActions: true

verifyStoreIntegrity: true
