allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

enablePrePostScripts: false

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@webdeveric/utils@1.2.0'
  - validate-package-exports@1.3.2
