name: Node.js CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  contents: read # for checkout

jobs:
  core:
    name: Continuous Integration Core Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          install: false # Audit before installing dependencies

      - name: Audit dependencies
        run: pnpm audit --audit-level=moderate --prod

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # TODO: restore this step once pnpm audit signatures stops failing for `devEngines.runtime` with `Missing registry metadata`.
      # - name: Verify registry signatures for installed packages
      #   run: pnpm audit signatures

      - name: Check spelling
        run: pnpm spellcheck

      - name: Typecheck
        run: pnpm typecheck

      - name: Linting
        run: pnpm lint

      - name: Build
        run: pnpm build

  tests:
    needs: core
    name: Continuous Integration Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.x, 24.x, 26.x]
        webpack-version: ['5.61.0', latest]
        dev-server-version: [4, 5, latest]
        css-loader-version: ['3.5.0', latest]
        exclude:
          - dev-server-version: latest
            webpack-version: '5.61.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          runtime: node@${{ matrix.node-version }}

      - name: Install specific dependency versions
        run: pnpm add -D webpack@${{ matrix.webpack-version }} webpack-dev-server@${{ matrix.dev-server-version }} css-loader@${{ matrix.css-loader-version }}

      - name: Test
        run: pnpm coverage
