name: Release

on:
  push:
    branches:
      - master

concurrency: release

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true
          install: false # Audit before installing dependencies

      - name: Audit dependencies
        run: pnpm audit --audit-level=moderate --prod

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Install npm for Trusted Publishing
        run: pnpm add --global npm@latest

      # TODO: restore this step once pnpm audit signatures stops failing for `devEngines.runtime` with `Missing registry metadata`.
      # - name: Verify registry signatures for installed packages
      #   run: pnpm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
