name: Weekly CI

on:
  schedule:
    - cron: '0 0 * * 2' # Tuesdays at 00:00 UTC

env:
  HUSKY: 0

permissions:
  contents: read # for checkout

jobs:
  weekly-ci:
    name: Weekly CI
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.x, 24.x, 26.x]
        webpack-version: ['5.61.0', latest]
        dev-server-version: [4, 5]
        css-loader-version: ['3.5.0', latest]
        include:
          - dev-serer-version: latest
            webpack-version: latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install specific dependency versions
        run: pnpm install webpack@${{ matrix.webpack-version }} webpack-dev-server@${{ matrix.dev-server-version }} css-loader@${{ matrix.css-loader-version }} --no-lockfile

      - name: Linting
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm coverage
